[project]
site_name = "Numbat"
site_url = "https://numbat.dev/doc/"
site_description = "Scientific calculator with full support for physical units"
site_author = "David Peter"
repo_url = "https://github.com/sharkdp/numbat"
docs_dir = "src"
site_dir = "site"
language = "en"
edit_uri = "edit/main/book/src/"
extra_css = ["stylesheets/extra.css"]

nav = [
  { "Getting started" = [
    "index.md",
    "tutorial.md",
    { "Example programs" = [
      "examples/index.md",
      "examples/example-acidity.md",
      "examples/example-barometric_formula.md",
      "examples/example-body_mass_index.md",
      "examples/example-factorial.md",
      "examples/example-pipe_flow_rate.md",
      "examples/example-medication_dosage.md",
      "examples/example-molarity.md",
      "examples/example-musical_note_frequency.md",
      "examples/example-paper_size.md",
      "examples/example-population_growth.md",
      "examples/example-recipe.md",
      "examples/example-voyager.md",
      "examples/example-xkcd_681.md",
      "examples/example-xkcd_687.md",
      "examples/example-xkcd_2585.md",
      "examples/example-xkcd_2812.md",
    ] },
  ] },

  { "Numbat basics" = [
    "basics/index.md",
    "basics/number-notation.md",
    "basics/unit-notation.md",
    "basics/operations.md",
    "basics/constant-definitions.md",
    "basics/unit-conversions.md",
    "basics/conversion-functions.md",
    "basics/function-definitions.md",
    "basics/conditionals.md",
    "basics/lists.md",
    "basics/structs.md",
    "basics/date-and-time.md",
    "basics/procedures.md",
  ] },


  { "Advanced topics" = [
    "advanced/index.md",
    "advanced/dimension-definitions.md",
    "advanced/unit-definitions.md",
    "examples/example-numbat_syntax.md",
    "type-system.md",
  ] },

  { "Standard library reference" = [
    "prelude/prelude.md",
    { "List of functions" = [
      "prelude/list-functions-math.md",
      "prelude/list-functions-lists.md",
      "prelude/list-functions-strings.md",
      "prelude/list-functions-datetime.md",
      "prelude/list-functions-other.md",
    ] },
    { "Predefined constants" = "prelude/list-constants.md" },
    { "List of units" = "prelude/list-units.md" },
  ] },


  { "Command-line version" = [
    "cli/installation.md",
    "cli/usage.md",
    "cli/customization.md",
  ] },

  { "Web version" = [
    "web/usage.md",
  ] },

  { "Other topics" = [
    "editor-integration.md",
    "comparison.md",
  ] },

  { "Support" = [
    "contact-us.md",
  ] },
]

[project.theme]
favicon = "assets/favicon.svg"
logo = "assets/favicon.svg"
font.code = "Fira Mono"
features = [
  "navigation.footer",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.tracking",
  "navigation.sections",
  "navigation.indexes",
  "navigation.top",
  "toc.follow",
  "content.action.edit",
]
palette.primary = "custom"
palette.accent = "custom"

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.extensions]
"admonition" = {}
"pymdownx.arithmatex" = { generic = true }
"pymdownx.highlight" = { anchor_linenums = true }
"pymdownx.superfences" = {}
"pymdownx.details" = {}
"pymdownx.keys" = {}

[project.extra]
extra_javascript = [
  "javascripts/mathjax.js",
  { url = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js", defer = true },
]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/sharkdp/numbat"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/kAaVTsat4D"
