[project]
site_name = "Numbat"
site_description = "Scientific calculator with full support for physical units"
site_url = "https://numbat.dev/doc/"
repo_url = "https://github.com/sharkdp/numbat"
docs_dir = "src"
site_dir = "site"
extra_css = ["stylesheets/extra.css"]

nav = [
  # Home
  { "Home" = "index.md" },

  # Getting started
  { "Introduction" = "introduction.md" },
  { "Tutorial" = "tutorial.md" },
  { "Example programs" = [
    "examples.md",
    "example-acidity.md",
    "example-barometric_formula.md",
    "example-body_mass_index.md",
    "example-factorial.md",
    "example-pipe_flow_rate.md",
    "example-medication_dosage.md",
    "example-molarity.md",
    "example-musical_note_frequency.md",
    "example-paper_size.md",
    "example-population_growth.md",
    "example-recipe.md",
    "example-voyager.md",
    "example-xkcd_681.md",
    "example-xkcd_687.md",
    "example-xkcd_2585.md",
    "example-xkcd_2812.md",
  ] },

  # Numbat language reference
  { "Basics" = [
    "basics.md",
    "number-notation.md",
    "unit-notation.md",
    "operations.md",
    "constant-definitions.md",
    "unit-conversions.md",
    "conversion-functions.md",
    "function-definitions.md",
    "conditionals.md",
    "lists.md",
    "structs.md",
    "date-and-time.md",
    "procedures.md",
  ] },
  { "Advanced" = [
    "advanced.md",
    "dimension-definitions.md",
    "unit-definitions.md",
    "example-numbat_syntax.md",
  ] },

  # Standard library reference
  { "The prelude" = "prelude.md" },
  { "Predefined functions" = [
    "predefined-functions.md",
    "list-functions-math.md",
    "list-functions-lists.md",
    "list-functions-strings.md",
    "list-functions-datetime.md",
    "list-functions-other.md",
  ] },
  { "Predefined constants" = "list-constants.md" },
  { "List of units" = "list-units.md" },

  # Command line tool
  { "CLI" = [
    "cli-installation.md",
    "cli-usage.md",
    "cli-customization.md",
  ] },

  # Web version
  { "Web version" = "web-usage.md" },

  # Notes for developers
  { "Type system" = "type-system.md" },

  # Other topics
  { "IDE / editor integration" = "editor-integration.md" },
  { "Comparison with other tools" = "comparison.md" },

  # Support
  { "Contact us" = "contact-us.md" },
]

[project.theme]
favicon = "assets/favicon.svg"
logo = "assets/favicon.svg"
font.code = "Fira Mono"
features = [
  "navigation.instant",
  "navigation.tracking",
  "navigation.sections",
  "navigation.expand",
  "navigation.top",
  "toc.follow",
]

[[project.theme.palette]]
scheme = "default"
toggle = { icon = "lucide/moon", name = "Switch to dark mode" }

[[project.theme.palette]]
scheme = "slate"
toggle = { icon = "lucide/sun", name = "Switch to light mode" }

[project.extensions]
"admonition" = {}
"pymdownx.arithmatex" = { generic = true }
"pymdownx.highlight" = { anchor_linenums = true }
"pymdownx.superfences" = {}
"pymdownx.details" = {}

[project.extra]
extra_javascript = [
  "javascripts/mathjax.js",
  { url = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js", defer = true },
]
